name       : i8kutils
version    : 1.42
release    : 1
source     :
    - https://launchpad.net/i8kutils/trunk/1.42/+download/i8kutils_1.42.tar.xz : 8764ee6d78e646965fbf1ba653cbfa6e05627eb9922389c132866431d7c3d802
license    : GPL-3.0
component  : system.utils
summary    : This package contains user-space programs for controling the fans on Dell laptops
description: |
    This package contains user-space programs for controling the fans on Dell laptops
setup      : |
    %patch -p1 < $pkgfiles/make.patch
build      : |
    %make
install    : |
    install -D -m 00755 i8kctl $installdir/usr/bin/i8kctl
    install -D -m 00755 i8kfan $installdir/usr/bin/i8kfan
    install -D -m 00755 i8kmon $installdir/usr/bin/i8kmon
    install -D -m 00755 probe_i8k_calls_time $installdir/usr/bin/probe_i8k_calls_time
    install -D -m 00644 i8kctl.1 $installdir/usr/share/man/man1/i8kctl.1
    install -D -m 00644 i8kmon.1 $installdir/usr/share/man/man1/i8kmon.1
    install -D -m 00644 $pkgfiles/i8kmon.service $installdir/usr/lib/systemd/system/i8kmon.service

