name       : i8kutils
version    : 1.43
release    : 2
source     :
    - https://launchpad.net/i8kutils/trunk/1.43/+download/i8kutils_1.43.tar.xz : 881a211c64f79be6a08c88864deda45280f0ce925ed9e2af180db2d93d364dcb
license    : GPL-3.0
component  : system.utils
summary    : This package contains user-space programs for controling the fans on Dell laptops
description: |
    This package contains a kernel driver and user-space programs for
    accessing the SMM BIOS of some Dell laptops. The SMM BIOS is used on many
    recent laptops to implement APM functionalities and to access custom
    hardware, for example the cooling fans and volume buttons.
rundeps    :
    - acpi
    - tcl
setup      : |
    %patch  -p1 < $pkgfiles/0001-Support-Stateless-configuration.patch
build      : |
    %make all probe_i8k_calls_time
install    : |
    install -d $installdir/usr/{bin,share/man/man1}
    install -D -m 00755 i8k{ctl,fan,mon} probe_i8k_calls_time $installdir/usr/bin
    install -D -m 00644 *.1 $installdir/usr/share/man/man1
    install -D -m 00644 dell-smm-hwmon.conf $installdir%libdir%/modprobe.d/dell-smm-hwmon.conf
    install -D -m 00644 i8kmon.conf $installdir/usr/share/i8kmon/i8kmon.conf
    install -D -m 00644 debian/i8kmon.service $installdir%libdir%/systemd/system/i8kmon.service
